### PR TITLE
GSK-278/task Disparate impact test

### PR DESCRIPTION
**Pull request by rabah-khalek**

### CODE REVIEW

**Comment by jmsquare** [comment]
The signature of the function is not correct to me. To me, the function should have 2 slices as argument and a dataset because:
1. As a user, the way we think about this test is comparing two slices inside the **same** dataset. There is no sense in giving the possibility to provide 2 different datasets as argument. It can even be misleading in the way we understand disparate impact
2. In AI Test v2, users will tend to create test suite so that slices_men + slice_women are "fixed" inputs that are shared between different fairness tests for gender and the dataset as "existing" input of the test suite. This logic of opening should be prepared from now. See image below. 
image
3. In the way, we create AI Test v2, it's important that the test function has the same argument as the argument in the UI that enables users to instantiate the test function. In the disparate impact case, the inputs that people will have in mind are the 2 population (ex: men and women) and the dataset. image
4. In terms of product strategy, It's really important to nudge users to create slices because our main product differentiator is creating business test. This is why it's crucial to have it as a test argument.

**Comment by rabah-khalek** [comment]
Thanks @jmsquare for these details. Ok I understand the logic and the motivation.
When we talk about passing slices as arguments, does that mean that instead of something like this:
```py
    def test_disparate_impact(self,
                              gsk_dataset: GiskardDataset,
                              protected_slice: Callable[[pd.DataFrame], pd.DataFrame],
                              unprotected_slice: Callable[[pd.DataFrame], pd.DataFrame],
                              model: GiskardModel,
                              positive_outcome,
                              threshold=0.8,
                              classification_label=None,
                              ) -> SingleTestResult:
```
where we can have for instance:
```py
protected_slice=lambda df: df[df.sex == "male"]
unprotected_slice=lambda df: df[df.sex == "female"]
```

**Comment by jmsquare** [comment]
Yes exactly. And dataset should also be an argument

**Comment by rabah-khalek** [comment]
related to https://github.com/Giskard-AI/giskard/pull/338

**Review by andreybavt — APPROVED** [review]

**Pull request merged**
