### PR TITLE
GSK-299 replaced df.head with df.iloc to fetch single row

### PR DESCRIPTION
**Pull request by princyiakov**
replaced df.head with df.iloc to fetch single row

### CODE REVIEW

**Review by rabah-khalek — COMMENTED** [review]
Is there a reason why it's not `df.iloc[0]` instead of `df.iloc[[0]]`?

**Comment by andreybavt** [comment]
I'm curious to know what's wrong with `head(1)`

**Comment by rabah-khalek** [comment]
If i recall correctly, this request was made by @jmsquare

**Comment by jmsquare** [comment]
Yes, it's just a very small change to make the error message much simpler to help the user to debug.

`Please make sure that prediction_function(df.head(1)) does not return an error`  is a bit more complex than `Please make sure that prediction_function(df.iloc[[0]]) does not return an error`. Because it adds the concept of "head"

I know this is very small ;)

**Pull request merged**
