### PR TITLE
reduced `nuniques_max` from 20 to 2

### PR DESCRIPTION
**Pull request by rabah-khalek**
A minor change in the value of `nuniques_max`

### CODE REVIEW

**Comment by rabah-khalek** [comment]
We thought 20 is a bit too much. We thought of many numerical categories that are integers having unique values < 20. So the max of 2 covers the most important case of binary categories.

**Comment by andreybavt** [comment]
ok, let's start with 2 and see if increasing makes sense

**Comment by andreybavt** [comment]
@rabah-khalek 
I think the check that could make most sense is:
1. for features marked as `numeric` that have less than **2** distinct values show a warning to mark feature as `category`
2. for features marked as `category` that have more than **50** (or even 100) distinct values show a warning to mark feature as `numeric`

The point is to cover the "extreme" cases by not having a single threshold

**Comment by jmsquare** [comment]
@andreybavt, for your second case (features marked as category that have more than 50), it could also be marked as `text`, not only `numeric`?
A way is to check if this categorical feature can be converted to numeric. If yes, we throw a warning to change it to `numeric`. If no, we throw a warning to turn it to `text`.
But I have the feeling we gonna have many warnings with this. What about having just your first.

Also the warning is not displaying well since we have 2 times the information (see below). Is there a way to display it better?
image

**Comment by rabah-khalek** [comment]
@andreybavt you're right, I'll fix the category case.
@jmsquare I'll add also the option of `text` not only `numeric`. 
There're two warnings in your case for each feature that fell into this condition.
I can certainly gather them and display one message only. Do you prefer this?

**Comment by jmsquare** [comment]
ok @rabah-khalek to me.  About the displaying issue, yes we can gather it. I was talking about the redundant line starting with : "f"Feature' [column]'.... Is there a way to remove it?

**Comment by rabah-khalek** [comment]
Ok, so:
- I fixed the display issue. 
- I migrated the test into the old `_validate_category_columns` but changed it into `_validate_column_categorization` for clarity
- I defined the following parameters:
  ```py
        nuniques_category = 5
        nuniques_numeric = 20
        nuniques_text = 200
  ```
  I think `nuniques_category=5` makes more sense than `2` as we have a lot of examples with categories > 2.
  I disentangled between numeric (where it could be integer for age) and text with an additional check on the type of the values for extra relevance. 

@jmsquare, have a go and let me know what you think.

**Comment by princyiakov** [comment]
_validate_column_categorization  throws error when the dataframe has a target and feature_types has no target.  For example, if you try to run the german credit scoring upload unit test on debug, you will see that the if condition throws an error as the feature_types doesn't contain target

**Comment by rabah-khalek** [comment]
ok @jmsquare I adjusted the thresholds to:
```
        nuniques_category = 2
        nuniques_numeric = 100
        nuniques_text = 1000
```
Hopefully with this, the demo projects don't trigger much warnings.

Thanks @princyiakov for this reminder. I fixed the unit test. Please have a look at it again!

**Pull request merged**
